# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml

since: 2013

# Set default keywords (Use a comma to separate)
keywords: ''

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: css/images/favicon.ico

# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar:
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg

# AboutPage background
about_big_image:
  [css/images/pose.jpg, https://source.unsplash.com/collection/954550/1920x1080]

# Homepage thumbnail
random_thumb: false

# Post Article's Content
post_catalog:
  enable: true

# Sidebar like in homepage, is necessary to disable [post_catalog]
post_sidebar:
  enable: false

# Content
fancybox: true

# Sidebar
sidebar: right
widgets:
  - search
  - social
  - recent_posts
  - category
  - tag
  - tagcloud
  - archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/anozon
  Weibo: https://anozon.me
  Twitter: https://twitter.com/anozon
  Facebook:
  Google-plus:
  Instagram:
  Pinterest:
  Flickr:
  email:

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname:
livere_shortname:
uyan_uid:
wumii:
gitment:
  owner: elzup
  repo: elzup/anozonbiyori-comment
  client_id: e8d3e5ce77d32fc8cbb7
  client_secret: 7e2e0bea0783bb552dd1515fc69f13a2f0d688d3

# valine:
#   appid: #Leancloud应用app_id，必填
#   appkey: #Leancloud应用app_key，必填
#   notify: false
#   verify: false
#   placeholder: comment
#   avatar:
#   pageSize: 10
#   visitor: true

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
google_site_verification:

# Miscellaneous
google_analytics: UA-49286104-10
gauges_analytics:
baidu_analytics:
tencent_analytics:
busuanzi_analytics: true
twitter:
google_plus:
fb_admins:
fb_app_id:

donate:
  enable: false

progressBar:
  enable: false

# Facebook SDK Support.
facebook_sdk:
  enable: false
  app_id: #<app_id>
  fb_admin: #<user_id>
  like_button: #true
  webmaster: #true

# Ad
ad:
  google_adsense_ad_client_id:
